app:
  camel.endpoint.activemq: activemq:queue:%s
  download.selenium.remoteUrl: http://host.docker.internal:4444/wd/hub
  schedule:
    updateMatchDatetimes: 0 0 9 * * ?
    updateMatchStats: 0 0,5,10,15,20,25,30,35,40,45,50,55 * * * ?
    finishMatchStats: 0 0 18 * * ?
    updateSquads: 0 0 10 * * ?

spring:
  flyway:
    locations: classpath:db/migration/table,classpath:db/migration/procedure/postgres,classpath:db/migration/data
  datasource:
    # default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
    open-in-view: false
