spring:
  config:
    import: classpath:application-production-secrets.yaml

---

# Put other production configs here

server:
  port: 8443
  ssl:
    enabled: true

spring:
  artemis:
    broker-url: tcp://artemis:61616
