app:
  camel.endpoint.activemq: activemq:queue:%s
  download.selenium.remoteUrl: http://host:4444/wd/hub
  schedule:
    #updateMatchStats: 0 40 * * * ?
    updateMatchStats: "-"
    #finishMatchStats: 0 14 * * * ?
    finishMatchStats: "-"

spring:
  flyway:
    locations: classpath:db/migration/table,classpath:db/migration/procedure/postgres,classpath:db/migration/data
  datasource:
    # default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
    open-in-view: false
  activemq:
    broker-url: tcp://localhost:61616
