app:
  route:
    parse: direct:parse
    fixtures: direct:fixtures
    d11Fixtures: direct:d11Fixtures
  download.selenium.remoteUrl: http://localhost:4444/wd/hub

spring:
  application:
    name: D11 CLI Application
  main.web-application-type: NONE
