api:
  basePath: 'http://192.168.1.3:8080'

spring:
  main:
    banner-mode: off

logging:
  level:
    root: INFO
    org.d11.boot.cli.D11BootCliApplication: ERROR
    org.springframework: ERROR
    org.apache: ERROR
    com.netflix: ERROR
  pattern:
    console: '%clr(${LOG_LEVEL_PATTERN:%5p}) %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}'
