CREATE TABLE IF NOT EXISTS premier_league (
    id SERIAL PRIMARY KEY,
    season_id INTEGER NOT NULL,
    name VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
