CREATE TABLE IF NOT EXISTS team_match_week_stat(
    id SERIAL PRIMARY KEY,
    team_id INTEGER NOT NULL REFERENCES team,
    match_week_id INTEGER NOT NULL REFERENCES match_week,
    matches_played INTEGER NOT NULL DEFAULT 0,
    matches_won INTEGER NOT NULL DEFAULT 0,
    matches_drawn INTEGER NOT NULL DEFAULT 0,
    matches_lost INTEGER NOT NULL DEFAULT 0,
    goals_for INTEGER NOT NULL DEFAULT 0,
    goals_against INTEGER NOT NULL DEFAULT 0,
    goal_difference INTEGER NOT NULL DEFAULT 0,
    points INTEGER NOT NULL DEFAULT 0,
    form_points INTEGER NOT NULL DEFAULT 0,
    form_match_points VARCHAR(255) NOT NULL,
    ranking INTEGER NOT NULL DEFAULT 0,
    previous_ranking INTEGER NOT NULL DEFAULT 0,
    home_matches_played INTEGER NOT NULL DEFAULT 0,
    home_matches_won INTEGER NOT NULL DEFAULT 0,
    home_matches_drawn INTEGER NOT NULL DEFAULT 0,
    home_matches_lost INTEGER NOT NULL DEFAULT 0,
    home_goals_for INTEGER NOT NULL DEFAULT 0,
    home_goals_against INTEGER NOT NULL DEFAULT 0,
    home_goal_difference INTEGER NOT NULL DEFAULT 0,
    home_points INTEGER NOT NULL DEFAULT 0,
    home_ranking INTEGER NOT NULL DEFAULT 0,
    away_matches_played INTEGER NOT NULL DEFAULT 0,
    away_matches_won INTEGER NOT NULL DEFAULT 0,
    away_matches_drawn INTEGER NOT NULL DEFAULT 0,
    away_matches_lost INTEGER NOT NULL DEFAULT 0,
    away_goals_for INTEGER NOT NULL DEFAULT 0,
    away_goals_against INTEGER NOT NULL DEFAULT 0,
    away_goal_difference INTEGER NOT NULL DEFAULT 0,
    away_points INTEGER NOT NULL DEFAULT 0,
    away_ranking INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

ALTER TABLE match_week
ADD CONSTRAINT match_week_premier_league_leader_id_fkey
FOREIGN KEY (premier_league_leader_id) REFERENCES team_match_week_stat(id);
