CREATE TABLE IF NOT EXISTS d11_team_season_stat(
    id SERIAL PRIMARY KEY,
    d11_team_id INTEGER NOT NULL REFERENCES d11_team,
    season_id INTEGER NOT NULL REFERENCES season,
    win_count INTEGER,
    matches_played INTEGER NOT NULL DEFAULT 0,
    matches_won INTEGER NOT NULL DEFAULT 0,
    matches_drawn INTEGER NOT NULL DEFAULT 0,
    matches_lost INTEGER NOT NULL DEFAULT 0,
    goals_for INTEGER NOT NULL DEFAULT 0,
    goals_against INTEGER NOT NULL DEFAULT 0,
    goal_difference INTEGER NOT NULL DEFAULT 0,
    points INTEGER NOT NULL DEFAULT 0,
    form_points INTEGER NOT NULL DEFAULT 0,
    form_match_points VARCHAR(255) NOT NULL,
    ranking INTEGER NOT NULL DEFAULT 0,
    previous_ranking INTEGER NOT NULL DEFAULT 0,
    home_matches_played INTEGER NOT NULL DEFAULT 0,
    home_matches_won INTEGER NOT NULL DEFAULT 0,
    home_matches_drawn INTEGER NOT NULL DEFAULT 0,
    home_matches_lost INTEGER NOT NULL DEFAULT 0,
    home_goals_for INTEGER NOT NULL DEFAULT 0,
    home_goals_against INTEGER NOT NULL DEFAULT 0,
    home_goal_difference INTEGER NOT NULL DEFAULT 0,
    home_points INTEGER NOT NULL DEFAULT 0,
    home_ranking INTEGER NOT NULL DEFAULT 0,
    away_matches_played INTEGER NOT NULL DEFAULT 0,
    away_matches_won INTEGER NOT NULL DEFAULT 0,
    away_matches_drawn INTEGER NOT NULL DEFAULT 0,
    away_matches_lost INTEGER NOT NULL DEFAULT 0,
    away_goals_for INTEGER NOT NULL DEFAULT 0,
    away_goals_against INTEGER NOT NULL DEFAULT 0,
    away_goal_difference INTEGER NOT NULL DEFAULT 0,
    away_points INTEGER NOT NULL DEFAULT 0,
    away_ranking INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
