CREATE TABLE IF NOT EXISTS card (
    id SERIAL PRIMARY KEY,
    match_id INTEGER NOT NULL REFERENCES match,
    team_id INTEGER NOT NULL REFERENCES team,
    player_id INTEGER NOT NULL REFERENCES player,
    time INTEGER NOT NULL,
    added_time INTEGER NOT NULL,
    card_type INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
