CREATE TABLE IF NOT EXISTS transfer_listing(
    id SERIAL PRIMARY KEY,
    transfer_day_id INTEGER NOT NULL REFERENCES transfer_day,
    player_id INTEGER NOT NULL REFERENCES player,
    team_id INTEGER NOT NULL REFERENCES team,
    d11_team_id INTEGER NOT NULL REFERENCES d11_team,
    position_id INTEGER NOT NULL REFERENCES position,
    ranking INTEGER NOT NULL DEFAULT 0,
    points INTEGER NOT NULL DEFAULT 0,
    form_points INTEGER NOT NULL DEFAULT 0,
    form_match_points VARCHAR(16) NOT NULL,
    points_per_appearance INTEGER NOT NULL DEFAULT 0,
    goals INTEGER NOT NULL DEFAULT 0,
    goal_assists INTEGER NOT NULL DEFAULT 0,
    own_goals INTEGER NOT NULL DEFAULT 0,
    goals_conceded INTEGER NOT NULL DEFAULT 0,
    clean_sheets INTEGER NOT NULL DEFAULT 0,
    yellow_cards INTEGER NOT NULL DEFAULT 0,
    red_cards INTEGER NOT NULL DEFAULT 0,
    substitutions_on INTEGER NOT NULL DEFAULT 0,
    substitutions_off INTEGER NOT NULL DEFAULT 0,
    man_of_the_match INTEGER NOT NULL DEFAULT 0,
    shared_man_of_the_match INTEGER NOT NULL DEFAULT 0,
    rating INTEGER NOT NULL DEFAULT 0,
    games_started INTEGER NOT NULL DEFAULT 0,
    games_substitute INTEGER NOT NULL DEFAULT 0,
    games_did_not_participate INTEGER NOT NULL DEFAULT 0,
    minutes_played INTEGER NOT NULL DEFAULT 0,
    new_player BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()::timestamp,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()::timestamp
);
